### PR TITLE
restructuring and moving content

### PR DESCRIPTION
**Pull request by renejeglinsky**

### CODE REVIEW

**Comment by vmikhailenko** [comment]
Apologies, but what order of the tutorials we will use from now?

**Comment by renejeglinsky** [comment]
I agree, this is hard to review w/o a proper preview. This is the "to be" structure:
image

**Comment by vmikhailenko** [comment]
Is the access from locally running app to a HANA removed?

**Comment by renejeglinsky** [comment]
Yes, we didn't want to describe that as it's more complicated and not really a starter scenario.

**Comment by renejeglinsky** [comment]
We could keep it as advanced and reference it as possible next step. Then you'd need to adapt that one accordingly.

**Comment by vmikhailenko** [comment]
> We could keep it as advanced and reference it as possible next step. Then you'd need to adapt that one accordingly.

If it will be the last, you do not have to adapt anything in the dependencies. 

You need to fetch the env from the CF (e.g. copypaste it) and remove everything except binding to HANA. I wonder if there is a command to do that without manual editing.

**Review by rjayasinghe — APPROVED** [review]
Content-wise this looks OK for me. Structure-wise I cannot tell because I can't see how this looks deployed at the moment.

**Comment by renejeglinsky** [comment]
> I agree, this is hard to review w/o a proper preview. This is the "to be" structure: image

I brought all those changes to a QA instance. There's no such type as mission or group, so you can't see the structure as it would be productive. But I'll add all the links to the QA server and that order one would do them later. So you can check out if the flow works as expected. It starts with the BAS setup for Java, not the general one as we didn't change that.

1. https://developers-qa.sap.com/tutorials/cp-cap-java-app-studio.html
2. https://developers-qa.sap.com/tutorials/cp-cap-java-custom-handler.html
3. https://developers-qa.sap.com/tutorials/cp-cap-java-reusable-service.html
4. https://developers-qa.sap.com/tutorials/cp-cap-java-service-reuse.html
5. https://developers-qa.sap.com/tutorials/cp-cap-java-custom-logic.html
6. https://developers-qa.sap.com/tutorials/cp-cap-java-security-local.html
7. https://developers-qa.sap.com/tutorials/cp-cap-java-deploy-cf.html
8. https://developers-qa.sap.com/tutorials/cp-cap-java-security-cf.html

**Comment by renejeglinsky** [comment]
In the 4th tutorial of the previous list, we mention that until that point no custom code has been needed. But we already did some custom coding in the 2nd tutorial. Could we move that to later? Or just delete that sentence and keep the order?

**Pull request merged**
